name = "intervinn/wirebox"
version = "0.1.2"
description = "Constructor-based Dependency Injection"
authors = ["intervinn"]
repository = "https://github.com/intervinn/wirebox"
license = "MIT"
includes = [
    "README.md",
    "LICENSE.md",
    "pesde.toml",
    "lib/**/*.luau"
]

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"